### ISSUE TITLE
STLs for printing would be nice too

### ISSUE THREAD

**Issue by aaraujo666** [maestrakos/warp#2]
And a little more clarity on the electronics? Like which servos are connected where on the servo board so that your code works as written.

Thanks!

**Comment by alexandrospetkos** [comment]
Ηi, I don't provide any stl files in GitHub because it is hard for other users to edit them and make changes using CAD software. I only provide a .step file which includes all the parts of the robot.
you can find it here:
https://github.com/maestrakos/warp/tree/master/resources/CAD/3D%20Models

I am working on a guide and I will try to publish it before the holidays. For the time being, yοu can check the comments at the top of this file for more clarity on the servo connections: https://github.com/maestrakos/warp/blob/master/source%20code/source_esp32/hardware.ino

/* - ::: HARDWARE :::
  This file is part of warp(Waste Allocation & Recognition Project).
  [hardware] This file manages the basic hardware functions.
  [BACK] [LEFT], LOWER JOINT (0, 0) : servo00,
  UPPER JOINT (0, 1) : servo02, SHLDR JOINT (0, 2) :servo08
  [FRONT][LEFT], LOWER JOINT (1, 0) : servo04,
  UPPER JOINT (1, 1) : servo06, SHLDR JOINT (1, 2) :servo09
  [FRONT][RIGHT], LOWER JOINT (2, 0) : servo05,
  UPPER JOINT (2, 1) : servo07, SHLDR JOINT (2, 2) :servo10
  [BACK] [RIGHT], LOWER JOINT (3, 0) : servo01,
  UPPER JOINT (3, 1) : servo03, SHLDR JOINT (3, 2) :servo11
*/
